### ISSUE TITLE
Resource Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/openbmc-uboot#3]
Stream is opened
https://github.com/facebook/openbmc-uboot/blob/504bf790da08db9b4a443566cf6ef577f9c7996a/tools/file2include.c#L38
Opened file never closed
https://github.com/facebook/openbmc-uboot/blob/504bf790da08db9b4a443566cf6ef577f9c7996a/tools/file2include.c#L47

**Comment by zhdaniel12** [comment]
will have upstream to fix this issue
