### ISSUE TITLE
Resource Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/openbmc-uboot#6]
Stream is opened

https://github.com/facebook/openbmc-uboot/blob/504bf790da08db9b4a443566cf6ef577f9c7996a/tools/sunxi-spl-image-builder.c#L259

Opened file never closed
https://github.com/facebook/openbmc-uboot/blob/504bf790da08db9b4a443566cf6ef577f9c7996a/tools/sunxi-spl-image-builder.c#L269

**Comment by williamspatrick** [comment]
Please submit upstream.
